'use client';
import { useEffect, useState } from 'react';
import { api, definirSessao, type SessionUser } from '../../utilitarios/api';

export default function LoginPage() {
  const [ready, setReady] = useState(false);
  useEffect(() => setReady(true), []);
  const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(false);
  async function submit(event: React.FormEvent) { event.preventDefault(); setLoading(true); setError(''); try { const data = await api<{ accessToken: string; user: SessionUser }>('/auth/login', { method: 'POST', body: JSON.stringify({ email: email.trim(), password }) }); definirSessao(data.accessToken, data.user); window.location.replace('/'); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Falha ao entrar.'); } finally { setLoading(false); } }
  return <main className="login-screen"><aside className="login-atmosphere" aria-label="Inspiração Inova Marmoraria"><div><small>INOVA MARMORARIA</small><h2>A natureza inspira.<br />A Inova transforma.</h2><p>Pedras, detalhes e possibilidades para dar forma a cada projeto.</p></div></aside><form className="login-card" onSubmit={submit}><img className="login-logo" style={{ width: 135, height: 70, objectFit: 'contain', objectPosition: 'left center', display: 'block', marginBottom: 14 }} src="/inova-logo.png" alt="Logo Inova Marmoraria"/><p className="eyebrow">INOVA MARMORARIA</p><h1>Entre para orçar</h1><p className="login-help">Use o acesso da sua equipe para criar e acompanhar os orçamentos.</p><label>E-mail<input value={email} onChange={(e) => setEmail(e.target.value)} type="email" name="email" autoComplete="username" required disabled={!ready} /></label><label>Senha<input value={password} onChange={(e) => setPassword(e.target.value)} type="password" name="password" autoComplete="current-password" required disabled={!ready} /></label>{error && <p role="alert" className="form-error">{error}</p>}<button className="primary-button" disabled={loading || !ready}>{loading ? 'Entrando…' : 'Entrar'}</button><small>Acesso exclusivo para a equipe Inova Marmoraria.</small></form></main>;
}
