import { test, expect, type Page } from '@playwright/test';
import { writeFileSync } from 'node:fs';
import { execFileSync } from 'node:child_process';

async function api(page: Page, method: string, path: string, data?: unknown) {
  const token = await page.evaluate(() => localStorage.getItem('inova_access_token'));
  return page.request.fetch(`/api${path}`, { method, headers: { authorization: `Bearer ${token}` }, data });
}

test('Orçamento rápido: teclado, projetos, serviços, PDF e detalhamento no mesmo orçamento', async ({ page }) => {
  await page.goto('/login');
  await page.getByLabel('E-mail', { exact: true }).fill('admin@inovamarmoraria.local');
  await page.getByLabel('Senha', { exact: true }).fill(process.env.INOVA_E2E_PASSWORD!);
  await page.getByRole('button', { name: 'Entrar', exact: true }).click();
  await expect(page.locator('#project-name')).toBeVisible();
  const catalog = await (await api(page, 'GET', '/catalog')).json();
  const material = catalog.materials.find((entry: any) => entry.name === 'Preto São Gabriel');
  const otherMaterial = catalog.materials.find((entry: any) => entry.name === 'Branco Dallas');
  const miter = catalog.services.find((entry: any) => entry.name === 'Acabamento 45° — Granito/Mármore');
  const customerName = `Cliente rápido ${Date.now()}`;
  expect((await api(page, 'POST', '/customers', { name: customerName, phone: `929${String(Date.now()).slice(-8)}` })).status()).toBe(201);
  await page.getByRole('button', { name: 'Selecionar cliente', exact: true }).click();
  await page.getByPlaceholder('Digite nome, telefone ou CPF').fill(customerName);
  await page.locator('.customer-result').filter({ hasText: customerName }).click();
  await page.getByRole('button', { name: 'Orçamento Rápido', exact: true }).click();
  const quick = page.locator('.quick-quote');
  await quick.locator('#project-name').fill('Cozinha rápida');
  await quick.locator('.picker-summary').click();
  await quick.getByRole('button').filter({ hasText: /^Preto São Gabriel/ }).click();
  const length = quick.getByLabel('Comprimento da peça 1 (m)', { exact: true });
  await length.fill('0,70'); await length.press('Enter');
  const width = quick.getByLabel('Largura da peça 1 (m)', { exact: true });
  await expect(width).toBeFocused(); await width.fill('0.30'); await width.press('Enter');
  const quantity = quick.getByLabel('Quantidade da peça 1', { exact: true });
  await expect(quantity).toBeFocused(); await quantity.press('Enter');
  await expect(quick.getByLabel('Comprimento da peça 2 (m)', { exact: true })).toBeFocused();
  // An unused insertion row must not prevent saving.
  await quick.getByRole('button', { name: '+ Acabamentos', exact: true }).click();
  const acabamento = page.getByRole('dialog').locator('fieldset').filter({ hasText: miter.name });
  await acabamento.getByLabel('Todos os lados', { exact: true }).check();
  await expect(acabamento.locator('input:checked')).toHaveCount(5);
  await acabamento.getByLabel('Superior', { exact: true }).uncheck();
  await acabamento.getByLabel('Direito', { exact: true }).uncheck();
  await page.getByRole('dialog').getByRole('button', { name: 'Concluir', exact: true }).click();
  await quick.getByRole('button', { name: 'Detalhar', exact: true }).first().click();
  await quick.getByRole('button', { name: '+ Recorte / cuba / furo', exact: true }).click();
  await quick.getByLabel('Tipo de recorte ou cuba').selectOption('SCULPTED_SINK');
  await quick.getByLabel('Tipo da peça 2', { exact: true }).selectOption('BACKSPLASH');
  await quick.getByLabel('Comprimento da peça 2 (m)', { exact: true }).fill('0,70');
  await quick.getByLabel('Largura da peça 2 (m)', { exact: true }).fill('0,15');
  await quick.getByLabel('Quantidade da peça 2', { exact: true }).fill('2');
  await quick.getByRole('button', { name: '+ Adicionar item', exact: true }).click();
  await expect(quick.locator('[data-quick-row]')).toHaveCount(3);
  await page.getByRole('button', { name: 'Adicionar projeto', exact: true }).click();
  await quick.locator('#project-name').fill('Banheiro rápido');
  await quick.locator('.picker-summary').click();
  await quick.getByRole('button').filter({ hasText: /^Branco Dallas/ }).click();
  await quick.getByLabel('Comprimento da peça 1 (m)', { exact: true }).fill('1,20');
  await quick.getByLabel('Largura da peça 1 (m)', { exact: true }).fill('0,60');
  await page.getByRole('tab', { name: 'Cozinha rápida', exact: true }).click();
  await expect(quick.getByLabel('Comprimento da peça 1 (m)', { exact: true })).toHaveValue('0,7');
  await page.getByLabel('Observações do orçamento', { exact: true }).fill('Conferir medidas na obra.');
  await page.waitForTimeout(450);
  await page.reload();
  await expect(page.locator('.quick-quote')).toBeVisible();
  await expect(page.getByRole('tab', { name: 'Banheiro rápido', exact: true })).toBeVisible();
  await page.screenshot({ path: '.test-artifacts/quick-desktop.png', fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  await expect(quick).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.screenshot({ path: '.test-artifacts/quick-mobile.png', fullPage: true });
  await page.setViewportSize({ width: 1440, height: 1000 });
  const responsePromise = page.waitForResponse(response => response.url().endsWith('/api/quotes') && response.request().method() === 'POST');
  await page.getByRole('button', { name: 'Salvar e abrir PDF', exact: true }).click();
  const response = await responsePromise;
  expect(response.status(), await response.text()).toBe(201);
  const quote = await response.json();
  await expect(page).toHaveURL(new RegExp(`/orcamentos/${quote.id}\\?pdf=1`));
  expect(quote.items).toHaveLength(2);
  const kitchen = quote.items.find((item: any) => item.projectName === 'Cozinha rápida');
  expect(kitchen.components).toHaveLength(2);
  expect(kitchen.components.every((piece: any) => piece.materialId === material.id)).toBe(true);
  expect(kitchen.components[0].edges.filter((edge: any) => edge.serviceId === miter.id).reduce((sum: number, edge: any) => sum + Number(edge.billedQuantity), 0)).toBe(1);
  expect(kitchen.cutouts).toHaveLength(1);
  expect(quote.items.find((item: any) => item.projectName === 'Banheiro rápido').materialId).toBe(otherMaterial.id);
  await expect(page.getByText('Como deseja gerar o PDF?')).toBeVisible();
  const pdf = await api(page, 'GET', `/quotes/${quote.id}/pdf?individualPrices=true&drawings=true`);
  expect(pdf.status()).toBe(200);
  writeFileSync('.test-artifacts/quick-quote.pdf', await pdf.body());
  const text = execFileSync('pdftotext', ['-', '-'], { input: await pdf.body() }).toString();
  expect(text).toContain('À VISTA'); expect(text).toContain('CARTÃO');
  expect(text).toContain(Number(quote.netTotal).toLocaleString('pt-BR', { minimumFractionDigits: 2, maximumFractionDigits: 2 }));
  expect(text).toContain((Math.round(Number(quote.netTotal) * 110) / 100).toLocaleString('pt-BR', { minimumFractionDigits: 2, maximumFractionDigits: 2 })); expect(text).not.toContain('ORDEM DE SERVIÇO');
  await page.getByRole('link', { name: 'Adicionar desenhos', exact: true }).first().click();
  await expect(page.getByRole('button', { name: 'Concluir detalhamento', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Concluir detalhamento', exact: true }).click();
  const updatedPromise = page.waitForResponse(response => response.url().endsWith(`/api/quotes/${quote.id}`) && response.request().method() === 'PUT');
  await page.getByRole('button', { name: 'Salvar orçamento', exact: true }).last().click();
  const updated = await updatedPromise;
  expect(updated.status()).toBe(200);
  await expect(page).toHaveURL(/\/orcamentos$/);
  const saved = await (await api(page, 'GET', `/quotes/${quote.id}`)).json();
  expect(saved.id).toBe(quote.id); expect(saved.netTotal).toBe(quote.netTotal);
  expect(saved.items.map((item: any) => item.id)).toEqual(quote.items.map((item: any) => item.id));
  expect(saved.items.flatMap((item: any) => item.components.map((piece: any) => piece.id))).toEqual(quote.items.flatMap((item: any) => item.components.map((piece: any) => piece.id)));
  // A real technical edit also retains the identities of the original pieces.
  const { itemSalvoParaEntrada } = await import('@inova/domain');
  const input = { customerId: saved.customerId, expectedUpdatedAt: saved.updatedAt, items: saved.items.map(itemSalvoParaEntrada) };
  input.items.find((item: any) => item.projectName === 'Cozinha rápida')!.cutouts[0].label = 'Cuba conferida na obra';
  const technicalEdit = await api(page, 'PUT', `/quotes/${quote.id}`, input);
  expect(technicalEdit.status(), await technicalEdit.text()).toBe(200);
  expect((await technicalEdit.json()).items.flatMap((item: any) => item.components.map((piece: any) => piece.id))).toEqual(saved.items.flatMap((item: any) => item.components.map((piece: any) => piece.id)));
  const fullPdf = await api(page, 'GET', `/quotes/${quote.id}/pdf?drawings=true`);
  expect(execFileSync('pdftotext', ['-', '-'], { input: await fullPdf.body() }).toString()).toContain('ORDEM DE SERVIÇO');
});
