import type { DraftComponent, DraftCutout, DraftItem } from './types';
type Service = { id: string; name: string; category: string; billingUnit: 'SQUARE_METER' | 'LINEAR_METER' | 'UNIT' | 'FIXED'; currentPrice: number };
type Props = { calculateCutout?: (cutout: DraftCutout) => number; cutouts: DraftCutout[]; components: DraftComponent[]; services: Service[]; serviceIds: string[]; serviceQuantities: DraftItem['serviceQuantities']; serviceAppliedValues: DraftItem['serviceAppliedValues']; onChange: (patch: Pick<DraftItem, 'cutouts' | 'serviceIds' | 'serviceQuantities' | 'serviceAppliedValues'>) => void };
const numeric = (value?: string) => Number((value ?? '').replace(',', '.')) || 0;
export function QuoteExtras({ calculateCutout, cutouts, components, services, serviceIds, serviceQuantities, serviceAppliedValues, onChange }: Props) {
  const cutoutCalculated = (cutout: DraftCutout) => { const service = services.find((entry) => entry.id === cutout.serviceId); if (!service) return 0; const quantity = service.billingUnit === 'SQUARE_METER' ? numeric(cutout.lengthCm) / 100 * (numeric(cutout.widthCm) / 100) * cutout.quantity : service.billingUnit === 'FIXED' ? 1 : cutout.quantity; return quantity > 0 ? quantity * service.currentPrice : 0; };
  const patchCutout = (index: number, patch: Partial<DraftCutout>) => onChange({ cutouts: cutouts.map((entry, current) => current === index ? { ...entry, ...patch } : entry), serviceIds, serviceQuantities, serviceAppliedValues });
  const addCutout = () => onChange({ cutouts: [...cutouts, { id: String(Date.now()), componentIndex: components.length ? 0 : undefined, cutoutType: 'SINK', label: 'Recorte / cuba', quantity: 1 }], serviceIds, serviceQuantities, serviceAppliedValues });
  const toggleService = (serviceId: string) => onChange({ cutouts, serviceIds: serviceIds.includes(serviceId) ? serviceIds.filter((id) => id !== serviceId) : [...serviceIds, serviceId], serviceQuantities, serviceAppliedValues });
  const nonLinearServices = services.filter((service) => service.billingUnit !== 'LINEAR_METER');
  return <section className="section"><div className="section-heading"><h2>Recortes, cubas e serviços</h2><span>opções compactas</span></div>
    <details className="compact-menu"><summary>Recortes e cubas {cutouts.length ? '(' + cutouts.length + ')' : ''}</summary><div className="compact-menu-content"><button type="button" className="text-button" onClick={addCutout}>+ Adicionar recorte/cuba</button>{cutouts.map((cutout, index) => { const calculated = calculateCutout ? calculateCutout(cutout) : cutoutCalculated(cutout); return <div className="cutout-row" key={cutout.id}><select value={cutout.cutoutType} onChange={(event) => patchCutout(index, { cutoutType: event.target.value as DraftCutout['cutoutType'] })}><option value="SINK">Cuba</option><option value="COOKTOP">Cooktop</option><option value="FAUCET_HOLE">Furo de torneira</option><option value="GENERIC_HOLE">Furo genérico</option><option value="OTHER">Outro</option></select><select value={cutout.componentIndex ?? ''} onChange={(event) => patchCutout(index, { componentIndex: event.target.value === '' ? undefined : Number(event.target.value) })}><option value="">Sem componente</option>{components.map((component, componentIndex) => <option key={component.id} value={componentIndex}>{component.label || 'Componente ' + (componentIndex + 1)}</option>)}</select><select value={cutout.serviceId ?? ''} onChange={(event) => patchCutout(index, { serviceId: event.target.value || undefined, appliedTotal: undefined })}><option value="">Sem cobrança de serviço</option>{services.filter((service) => service.billingUnit !== 'LINEAR_METER').map((service) => <option key={service.id} value={service.id}>{service.name}</option>)}</select><input value={cutout.label} onChange={(event) => patchCutout(index, { label: event.target.value })} placeholder="Descrição" /><input inputMode="decimal" value={cutout.lengthCm ?? ''} onChange={(event) => patchCutout(index, { lengthCm: event.target.value })} placeholder="Comprimento (cm)" /><input inputMode="decimal" value={cutout.widthCm ?? ''} onChange={(event) => patchCutout(index, { widthCm: event.target.value })} placeholder="Largura (cm)" /><input inputMode="decimal" value={cutout.positionXCm ?? ''} onChange={(event) => patchCutout(index, { positionXCm: event.target.value })} placeholder="Posição X (cm)" /><input inputMode="decimal" value={cutout.positionYCm ?? ''} onChange={(event) => patchCutout(index, { positionYCm: event.target.value })} placeholder="Posição Y (cm)" />{cutout.serviceId && <><small>Calculado: R$ {calculated.toLocaleString('pt-BR', { minimumFractionDigits: 2 })}</small><input inputMode="decimal" value={cutout.appliedTotal ?? calculated.toFixed(2).replace('.', ',')} onChange={(event) => patchCutout(index, { appliedTotal: event.target.value })} placeholder="Valor final do recorte/cuba" /></>}<button type="button" onClick={() => onChange({ cutouts: cutouts.filter((_, current) => current !== index), serviceIds, serviceQuantities, serviceAppliedValues })}>Remover</button></div>; })}</div></details>
    <details className="compact-menu"><summary>Adicionar serviços e acabamentos {serviceIds.length ? '(' + serviceIds.length + ')' : ''}</summary><div className="compact-menu-content">{nonLinearServices.map((service) => { const selected = serviceIds.includes(service.id); return <div className={'compact-option ' + (selected ? 'selected' : '')} key={service.id}><button type="button" className="service-main" onClick={() => toggleService(service.id)}><span><strong>{service.name}</strong><small>{service.category} · R$ {service.currentPrice.toLocaleString('pt-BR')} · {service.billingUnit === 'SQUARE_METER' ? 'por m²' : service.billingUnit === 'UNIT' ? 'por unidade' : 'valor fixo'}</small></span><b>{selected ? '✓' : '+'}</b></button>{selected && service.billingUnit === 'UNIT' && <input inputMode="decimal" placeholder="Quantidade" value={serviceQuantities[service.id] ?? ''} onChange={(event) => onChange({ cutouts, serviceIds, serviceQuantities: { ...serviceQuantities, [service.id]: event.target.value }, serviceAppliedValues })} />}</div>; })}</div></details>
  </section>;
}
