CREATE TYPE "ExecutionStatus" AS ENUM ('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED');
ALTER TABLE "Quote" ADD COLUMN "executionStatus" "ExecutionStatus" NOT NULL DEFAULT 'NOT_STARTED';
ALTER TABLE "Quote" ADD COLUMN "approvedAt" TIMESTAMP(3);
ALTER TABLE "Quote" ADD COLUMN "completedAt" TIMESTAMP(3);
